### ISSUE TITLE
Compilation error on RH6

### ISSUE THREAD

**Issue by fhahne** [rstudio/httpuv#32] opened 2014-07-22 17:02 UTC
I am getting this when trying to compile on Redhat 6:

gcc -std=gnu99 --std=c89 -pedantic -Wall -Wextra -Wno-unused-parameter -I/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include -I/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv-private -I/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/src -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g -O2  -fpic -c src/unix/async.c -o src/unix/async.o
In file included from /itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:67,
                 from src/unix/async.c:25:
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv-private/uv-unix.h:131: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'uv_rwlock_t'
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv-private/uv-unix.h:148: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'uv_barrier_t'
In file included from src/unix/async.c:25:
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:386: warning: 'struct addrinfo' declared inside parameter list
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1881: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1882: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1883: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1884: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1885: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1886: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1887: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1888: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1923: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1924: error: expected ')' before '_' token
/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv/include/uv.h:1925: error: expected ')' before '_' token
In file included from src/unix/internal.h:35,
                 from src/unix/async.c:26:
src/unix/linux-syscalls.h:129: warning: type defaults to 'int' in declaration of 'sigset_t'
src/unix/linux-syscalls.h:129: error: expected ';', ',' or ')' before '_' token
make[1]: **\* [src/unix/async.o] Error 1
make[1]: Leaving directory `/itox_scratch/tmp/Rtmp07aKZV/devtools12d5940aeba88/httpuv-master/src/libuv'
make: **\* [libuv.a] Error 2
ERROR: compilation failed for package 'httpuv'
- removing '/usr/prog/pcsi/RH6/R/source/R-3-1-0/localPackages/httpuv'
  Error: Command failed (1)

**Comment by adamjstewart** [comment] 2017-01-30 19:13
I'm also seeing this same error with GCC 6.1.0 on CentOS 6:
```
/blues/gpfs/home/software/spack-0.10.0/lib/spack/env/gcc/gcc --std=c89 -pedantic -Wall -Wextra -Wno-unused-parameter -I/scratch/ajstewart/spack-stage/spack-stage-gd_bLD/httpuv/src/libuv/include -I/scratch/ajstewart/spack-stage/spack-stage-gd_bLD/httpuv/src/libuv/include/uv-private -I/scratch/ajstewart/spack-stage/spack-stage-gd_bLD/httpuv/src/libuv/src -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC  -fpic -c src/unix/async.c -o src/unix/async.o
In file included from /scratch/ajstewart/spack-stage/spack-stage-gd_bLD/httpuv/src/libuv/include/uv.h:67:0,
                 from src/unix/async.c:25:
/scratch/ajstewart/spack-stage/spack-stage-gd_bLD/httpuv/src/libuv/include/uv-private/uv-unix.h:131:9: error: unknown type name ‘pthread_rwlock_t’
 typedef pthread_rwlock_t uv_rwlock_t;
         ^~~~~~~~~~~~~~~~
/scratch/ajstewart/spack-stage/spack-stage-gd_bLD/httpuv/src/libuv/include/uv-private/uv-unix.h:148:9: error: unknown type name ‘pthread_barrier_t’
 typedef pthread_barrier_t uv_barrier_t;
         ^~~~~~~~~~~~~~~~~
```
Should it be using `--std=gnu99` instead of `--std=c89`?

**Comment by jcheng5** [comment] 2017-01-30 20:01
How are you installing GCC 6.1.0? It looks like spack is a package manager of some kind? If you could give me instructions for reproducing that would be great--I haven't been able to reproduce these RH6 compile errors in the past.

**Comment by adamjstewart** [comment] 2017-01-30 20:07
Yes, Spack is a package manager that can be downloaded from https://github.com/LLNL/spack. I'm a developer, so I can help you if you run into any problems. After cloning the repository, you should be able to run:
```
export PATH=spack/bin:$PATH
spack compiler find  # should pick up your system compiler
spack install gcc@6.1.0  # or whatever version
# will print out an installation path when finished
spack compiler add <installation path of GCC 6>
spack install --verbose r-httpuv
```
In the meantime, I'll try building with my system compiler and see if the same problem occurs for me. I can also try on Fedora 25 as well.

**Comment by wch** [comment] 2018-04-13 20:27
I believe this should be fixed now. If it is still a problem, please re-open or file a new issue.

**Closed by wch** 2018-04-13 20:27 UTC
