### ISSUE TITLE
Installation fails on OpenBSD 5.9 with undefined kvm_* symbols errors

### ISSUE THREAD

**Issue by tlevine** [rstudio/httpuv#61] opened 2016-06-11 07:05 UTC
Here are error messages from my attempt to install.

```
/usr/local/lib/R/bin/exec/R:/usr/local/lib/R/library/httpuv/libs/httpuv.so: undefined symbol 'kvm_open'
/usr/local/lib/R/bin/exec/R:/usr/local/lib/R/library/httpuv/libs/httpuv.so: undefined symbol 'kvm_close'
/usr/local/lib/R/bin/exec/R:/usr/local/lib/R/library/httpuv/libs/httpuv.so: undefined symbol 'kvm_getprocs'
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/library/httpuv/libs/httpuv.so':
  Cannot load specified object
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/library/httpuv’
```

They occurred both in the present CRAN version and in the current HEAD of master, commit 6aeca57b8a4302a11e88d4eef07d7a8ceed742a9 on OpenBSD 5.9.

```
> uname -a
OpenBSD blautkraut 5.9 GENERIC.MP#1888 amd64
```

I think I have the right header file, but I don't really know anything about C++. The other included files are in the same directory, so I think the paths are set up correctly.

```
> grep kvm_ /usr/include/kvm.h
 * Flag for kvm_open* that disables opening of any files. We're just
typedef struct __kvm kvm_t;
int       kvm_close(kvm_t *);
int       kvm_dump_inval(kvm_t *);
int       kvm_dump_mkheader(kvm_t *, off_t);
int       kvm_dump_wrtheader(kvm_t *, FILE *, int);
char    **kvm_getargv(kvm_t *, const struct kinfo_proc *, int);
char    **kvm_getenvv(kvm_t *, const struct kinfo_proc *, int);
char     *kvm_geterr(kvm_t *);
int       kvm_getloadavg(kvm_t *, double [], int);
          kvm_getfiles(kvm_t *, int, int, size_t, int *);
          kvm_getprocs(kvm_t *, int, int, size_t, int *);
int       kvm_nlist(kvm_t *, struct nlist *);
kvm_t    *kvm_open(const char *, const char *, const char *, int, const char *);
kvm_t    *kvm_openfiles(const char *, const char *, const char *,
ssize_t   kvm_read(kvm_t *, unsigned long, void *, size_t)
ssize_t   kvm_write(kvm_t *, unsigned long, const void *, size_t)
```

**Comment by feinerer** [comment] 2016-07-14 07:07
Confirmed also on OpenBSD 6.0-beta (GENERIC.MP) #2268 amd64.

The problem is that httpuv.so is not linked with `-lkvm` (see e.g. https://marc.info/?l=openbsd-ports&m=143204925608913&w=2)

`LDFLAGS=-lkvm` in `~/.R/Makevars` helps but this should be set automatically by the package installation.

**Comment by wch** [comment] 2018-04-13 19:32
Closing because we have incorporated the fix.

**Closed by wch** 2018-04-13 19:32 UTC
